---
# Remove any old Ceph keys added to the main keyring.
- name: Clean up old key
  apt_key:
    id: E84AC2C0460F3994
    state: absent
  become: true

- name: Ensure keys directory exists
  file:
    path: "{{ cephadm_apt_key_path | dirname }}"
    owner: root
    group: root
    mode: "0755"
    state: directory
  when: not cephadm_custom_repos | bool
  become: true

- name: Ensure keys exist
  get_url:
    url: "{{ cephadm_apt_key_url }}"
    dest: "{{ cephadm_apt_key_path }}"
    owner: root
    group: root
    mode: "0644"
  when: not cephadm_custom_repos | bool
  become: true

- name: Ensure Ceph repositories are defined
  apt_repository:
    repo: "deb [signed-by={{ cephadm_apt_key_path }}] https://download.ceph.com/debian-{{ item }}/ {{ cephadm_apt_repo_dist }} main"
    state: "{{ 'present' if item == cephadm_ceph_release else 'absent' }}"
  when: not cephadm_custom_repos | bool
  become: true
  loop: "{{ cephadm_ceph_releases }}"

- name: Install cephadm package
  apt:
    name: "cephadm"
    state: "{{ 'latest' if cephadm_package_update | bool else 'present' }}"
    update_cache: true
  become: true

- name: Install ceph cli on mon hosts
  ansible.builtin.package:
    name: "ceph-common"
    state: present
  become: true
  changed_when: true
  when:
    - cephadm_install_ceph_cli
    - inventory_hostname in groups['mons']
